# Generated by Django 6.0.1 on 2026-01-12 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messmember',
            name='role',
        ),
        migrations.AddField(
            model_name='mess',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messmember',
            name='mess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_manage.mess'),
        ),
    ]
