# Generated by Django 6.0.1 on 2026-01-13 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manage', '0002_remove_messmember_role_mess_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messmember',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mess',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
