# Generated by Django 6.0.1 on 2026-01-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manage', '0003_messmember_status_alter_mess_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmember',
            name='status',
            field=models.BooleanField(choices=[(0, 'Active'), (1, 'Deactive')], default=False),
        ),
    ]
