# Generated by Django 6.0.1 on 2026-01-13 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manage', '0004_alter_messmember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messmember',
            unique_together={('mess', 'user')},
        ),
    ]
