# Generated by Django 6.0.1 on 2026-01-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manage', '0005_alter_messmember_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.PositiveIntegerField()),
                ('deposit_details', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='meal_manage.messmember')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_manage.mess')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
