# Generated by Django 6.0.1 on 2026-01-14 04:57

import django.core.validators
import django.db.models.deletion
import meal_manage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manage', '0006_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), meal_manage.models.meal_validator])),
                ('lunch', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), meal_manage.models.meal_validator])),
                ('dinner', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), meal_manage.models.meal_validator])),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal', to='meal_manage.messmember')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_manage.mess')),
            ],
        ),
    ]
