# Generated by Django 6.0.1 on 2026-01-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_manage', '0007_dailymeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mess',
            options={'verbose_name': 'Mess', 'verbose_name_plural': 'Mess'},
        ),
        migrations.AlterModelOptions(
            name='messmember',
            options={'verbose_name': 'Mess Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_cost', models.PositiveIntegerField()),
                ('meal_cost_details', models.CharField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost', to='meal_manage.messmember')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_manage.mess')),
            ],
        ),
    ]
