# Generated by Django 6.0 on 2025-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_meal_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='created',
            field=models.DateTimeField(verbose_name='DateFiled'),
        ),
    ]
